import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(12,GPIO.OUT)
GPIO.setup(13,GPIO.OUT)
GPIO.setup(14,GPIO.OUT)
GPIO.setup(15,GPIO.OUT)
GPIO.setup(16,GPIO.OUT)
GPIO.setup(17,GPIO.OUT)
GPIO.setup(18,GPIO.OUT)
GPIO.setup(19,GPIO.OUT)
while True:
    print("Relay 1 On")
    GPIO.output(12,GPIO.HIGH)
    time.sleep(2)
    print("Relay 1 Off")
    GPIO.output(12,GPIO.LOW)
    print("Relay 2 On")
    GPIO.output(13,GPIO.HIGH)
    time.sleep(2)
    print("Relay 2 Off")
    GPIO.output(13,GPIO.LOW)
    print("Relay 3 On")
    GPIO.output(14,GPIO.HIGH)
    time.sleep(2)
    print("Relay 3 Off")
    GPIO.output(14,GPIO.LOW)
    print("Relay 4 On")
    GPIO.output(15,GPIO.HIGH)
    time.sleep(2)
    print("Relay 4 Off")
    GPIO.output(15,GPIO.LOW)
    print("Relay 5 On")
    GPIO.output(16,GPIO.HIGH)
    time.sleep(2)
    print("Relay 5 Off")
    GPIO.output(16,GPIO.LOW)
    print("Relay 6 On")
    GPIO.output(17,GPIO.HIGH)
    time.sleep(2)
    print("Relay 6 Off")
    GPIO.output(17,GPIO.LOW)
    print("Relay 7 On")
    GPIO.output(18,GPIO.HIGH)
    time.sleep(2)
    print("Relay 7 Off")
    GPIO.output(18,GPIO.LOW)
    print("Relay 8 On")
    GPIO.output(19,GPIO.HIGH)
    time.sleep(2)
    print("Relay 8 Off")
    GPIO.output(19,GPIO.LOW)
    time.sleep(2)